-- 1. LIMPEZA E CRIAÇÃO DO SCHEMA
DROP DATABASE IF EXISTS ProjetoBDFaculdade;
CREATE DATABASE ProjetoBDFaculdade;
USE ProjetoBDFaculdade;

-- 2. CRIAÇÃO DAS TABELAS (ORDEM HIERÁRQUICA)

CREATE TABLE DEPARTAMENTO (
    Cod_Departamento INT PRIMARY KEY,
    Nome_Departamento VARCHAR(40) NOT NULL
);

CREATE TABLE PROFESSOR (
    Cod_Professor INT PRIMARY KEY,
    Nome_Professor VARCHAR(40) NOT NULL,
    Sobrenome_Professor VARCHAR(40) NOT NULL,
    Status_Ativo BOOLEAN NOT NULL DEFAULT TRUE,
    Cod_Departamento INT NOT NULL,
    CONSTRAINT FK_PROF_DEPT FOREIGN KEY (Cod_Departamento) REFERENCES DEPARTAMENTO(Cod_Departamento)
);

CREATE TABLE CURSO (
    Cod_Curso INT PRIMARY KEY,
    Nome_Curso VARCHAR(40) NOT NULL,
    Cod_Departamento INT NOT NULL,
    CONSTRAINT FK_CURSO_DEPT FOREIGN KEY (Cod_Departamento) REFERENCES DEPARTAMENTO(Cod_Departamento)
);

CREATE TABLE DISCIPLINA (
    Cod_Disciplina INT PRIMARY KEY,
    Nome_Disciplina VARCHAR(30) NOT NULL,
    Descricao VARCHAR(200),
    Carga_Horaria INT NOT NULL,
    Num_Alunos INT NOT NULL,
    Cod_Departamento INT NOT NULL,
    CONSTRAINT FK_DISC_DEPT FOREIGN KEY (Cod_Departamento) REFERENCES DEPARTAMENTO(Cod_Departamento)
);

CREATE TABLE TURMA (
    Cod_Turma INT PRIMARY KEY,
    Periodo VARCHAR(10) NOT NULL,
    Num_Alunos INT NOT NULL,
    Data_Inicio DATE NOT NULL,
    Data_Fim DATE NOT NULL,
    Cod_Curso INT NOT NULL,
    CONSTRAINT FK_TURMA_CURSO FOREIGN KEY (Cod_Curso) REFERENCES CURSO(Cod_Curso)
);

CREATE TABLE ALUNO (
    RA VARCHAR(8) PRIMARY KEY,
    Nome_Aluno VARCHAR(25) NOT NULL,
    Sobrenome_Aluno VARCHAR(40) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    Status_Matricula VARCHAR(1) NOT NULL,
    Sexo VARCHAR(1) NOT NULL,
    Filiacao VARCHAR(80),
    Endereco VARCHAR(100),
    Cod_Turma INT NOT NULL,
    Cod_Curso INT NOT NULL,
    CONSTRAINT FK_ALUNO_TURMA FOREIGN KEY (Cod_Turma) REFERENCES TURMA(Cod_Turma),
    CONSTRAINT FK_ALUNO_CURSO FOREIGN KEY (Cod_Curso) REFERENCES CURSO(Cod_Curso)
);

CREATE TABLE HISTORICO (
    Cod_Historico INT PRIMARY KEY,
    RA VARCHAR(8) NOT NULL,
    Periodo_Realizacao INT NOT NULL,
    CONSTRAINT FK_HIST_ALUNO FOREIGN KEY (RA) REFERENCES ALUNO(RA)
);

-- 3. TABELAS ASSOCIATIVAS (MUITOS-PARA-MUITOS)

CREATE TABLE PROF_DISCIPLINA (
    Cod_Professor INT NOT NULL,
    Cod_Disciplina INT NOT NULL,
    PRIMARY KEY (Cod_Professor, Cod_Disciplina),
    CONSTRAINT FK_PD_PROF FOREIGN KEY (Cod_Professor) REFERENCES PROFESSOR(Cod_Professor),
    CONSTRAINT FK_PD_DISC FOREIGN KEY (Cod_Disciplina) REFERENCES DISCIPLINA(Cod_Disciplina)
);

CREATE TABLE CURSO_DISCIPLINA (
    Cod_Curso INT NOT NULL,
    Cod_Disciplina INT NOT NULL,
    PRIMARY KEY (Cod_Curso, Cod_Disciplina),
    CONSTRAINT FK_CD_CURSO FOREIGN KEY (Cod_Curso) REFERENCES CURSO(Cod_Curso),
    CONSTRAINT FK_CD_DISC FOREIGN KEY (Cod_Disciplina) REFERENCES DISCIPLINA(Cod_Disciplina)
);

CREATE TABLE DISC_HIST (
    Cod_Historico INT NOT NULL,
    Cod_Disciplina INT NOT NULL,
    Nota DECIMAL(4,2) NOT NULL,
    Frequencia INT NOT NULL,
    PRIMARY KEY (Cod_Historico, Cod_Disciplina),
    CONSTRAINT FK_DH_HIST FOREIGN KEY (Cod_Historico) REFERENCES HISTORICO(Cod_Historico),
    CONSTRAINT FK_DH_DISC FOREIGN KEY (Cod_Disciplina) REFERENCES DISCIPLINA(Cod_Disciplina)
);

-- 4. INSERÇÃO DE DADOS PARA O PORTFÓLIO (DML)

INSERT INTO DEPARTAMENTO VALUES (1, 'Tecnologia da Informação');
INSERT INTO CURSO VALUES (1, 'Ciência da Computação', 1);
INSERT INTO DISCIPLINA VALUES (1, 'Banco de Dados I', 'Modelagem e SQL', 80, 30, 1);
INSERT INTO PROFESSOR VALUES (1, 'Fábio', 'Boson', 1, 1);
INSERT INTO TURMA VALUES (101, 'Noturno', 30, '2025-02-01', '2025-07-01', 1);

-- Inserindo os alunos com RAs de 8 dígitos
INSERT INTO ALUNO VALUES 
('20260001', 'Danielli', 'Arçari', '000.000.000-00', 'M', 'F', 'N/A', 'Rua 1', 101, 1),
('20260002', 'Álvaro', 'Arçari', '111.111.111-11', 'M', 'M', 'N/A', 'Rua 1', 101, 1),
('20260003', 'Leonardo', 'Arçari', '222.222.222-22', 'M', 'M', 'N/A', 'Rua 1', 101, 1);

-- 5. CONSULTA DE TESTE
SELECT * FROM ALUNO;